language: python
python:
- '3.5'
install:
- python setup.py install
- pip install -r docs/requirements.txt
script:
- python setup.py test --addopts -v
- cd docs && make doctest && cd -
- python setup.py sdist
notifications:
  email:
    on_success: change
    on_failure: change

deploy:
  provider: pypi
  user:
    secure: "WAkraMTh/rX0Eiiqkg0c/cJoYksLDOMgGLhEcqu+O9JQxCBq2G6u/f0qGm48EyJon22LfvUKZYOVnNXf1FHV9OK17II0aK88A2xSbU5Jruf0CPVq4tK+Ee1ZP20UP/sMVPKyCkVcxgF8VEJTpw0ahguyXTBFgvVhxte5xKW0nOmJSDQl0mGBSyvXxLU85tcj4OIDP1lYTb9nLkal1KNHQDRrV+FaoqzJwc2+KyrqDTAZaqp05edAANzxuwElUKARMgrbRQSebxsZl/dKUP3ywWfPNW5hyIApQBNtoeGklh0Ibmm45bwTfATZGL4HXxOXjQvtREko7zslxzOlSWYVW/BciqF1KHwybc36ZmjVfbfg19wJbh8rnEmd+9pPfvUifArxOm6/UIXvoHnYct3kIijuGXjD39rgtH+TSweK4OIW7YD9+oROopMJ/Us0IJ8K1kvq00OCjZuG2t0y1s6TCQeaXUK/S49SaFDV9yFlsUGwDFCJD6b7F4m87tqiKsC5LJtJeicEGN81f5ehkhvtWzPdiPNmNMRXf+oPFvquwH/IcPGcPETgfbMMbQWrgsx3ppOk1cQwghoqq8qEJ4Bs2u9gEc+q+ASDBrHxcy+VU8j0NTMMXd7t++L61SkFEqMkmYajQ+4TGsidCSIv1nrI189jOvft8qiqlRimuZUlr8Q="
  password:
    secure: "b3f+IZ7TxN781jdG3t2VbZ+YyCUeIaYe2KGeYArYE7/hzynbz8Jz8LN3odGd9hFgzMvqZGlNrlRgyd4tO+XEsgEAjaDKOwY4lD1/hLHd04UwylYtflk9q+dgE3ThEKkdZBxbXwvuSmeFp4HcaRGWcNaCSWlueY++LN1jZAI8km8Z3mpKewS6OZeUu644UXL/gaXXr8AJaqbNxtPmiyCT0rkwLi+5m/AbRB9gDx5JO4OnJOr3u23Cuczcx79/bA2rLZor0khOGkPmqfAIh+MPky53SRG1dFR//Dx5e621nzk0AqLzfwZ5WrHBPOto37gma/eKQitJlvCXiS9AXPxu+CMDzF6w3ZuNVQF6MegPQoVQKsIH3Xv8pfJzg9ZK+XDW27HxrnGVk+rZgz7Wgyl5eIY7Rgn6r6DIlo0orbIXLPDe9lANIIuq4FkebSP2FZhW9kp0sPkGllZMuGuYA2tsPi1t8K2XrSs97ZTtod8qzHB73zAy57fX2UVY7xg9+w/YdWNPqmVqx/L5zCKFLGnP4VvL/fA8fijEQTHTCbGMdJ0zbnt93S/ZYrcl8tcN1CKQUNTrSMfmFjeF0HVY+t2FGIZBjEDX6o2zMVWKhQvJATiFSofxmwqZuEsF2Lm2JMK/G8updCQ98nH134K7XRE/3RupBQL748H8gyfsIrFqd6U="
  on:
    tags: true
